name: Deploy cache worker

on:
  push:
    paths:
      - 'cache/**'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Publish
        uses: cloudflare/wrangler-action@master
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'cache'
